<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="unittest.suite._ErrorHolder-20230830155959" tests="1" file="unittest/suite.py" time="0.000" timestamp="0001-01-01T00:00:00" failures="0" errors="1" skipped="0">
	<testcase classname="" name="setUpClass (__main__.TestAmazonApp)" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'dict' object has no attribute 'setCapability'"><![CDATA[Traceback (most recent call last):
  File "C:\Users\Lenovo\OneDrive - bridgeaxis.com\Documents\Graffitecs task\amazon_test.py", line 22, in setUpClass
    capabilities.setCapability("newCommandTimeout", 1000)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'setCapability'
]]></error>
	</testcase>
</testsuite>
