<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="unittest.suite._ErrorHolder-20230830155648" tests="1" file="unittest/suite.py" time="0.000" timestamp="0001-01-01T00:00:00" failures="0" errors="1" skipped="0">
	<testcase classname="" name="setUpClass (__main__.TestAmazonApp)" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="SessionNotCreatedException" message="Message: A new session could not be created. Details: 'newCommandTimeout' must be of type number
Stacktrace:
SessionNotCreatedError: A new session could not be created. Details: 'newCommandTimeout' must be of type number
    at AndroidUiautomator2Driver.createSession (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\driver.ts:273:13)
    at AndroidUiautomator2Driver.createSession (C:\Users\Lenovo\.appium\node_modules\appium-uiautomator2-driver\lib\driver.js:189:43)
    at AppiumDriver.createSession (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\lib\appium.js:374:56)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)"><![CDATA[Traceback (most recent call last):
  File "C:\Users\Lenovo\OneDrive - bridgeaxis.com\Documents\Graffitecs task\amazon_test.py", line 23, in setUpClass
    cls.driver = webdriver.Remote(appium_server_url, capabilities)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\appium\webdriver\webdriver.py", line 257, in __init__
    super().__init__(
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\appium\webdriver\webdriver.py", line 346, in start_session
    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: A new session could not be created. Details: 'newCommandTimeout' must be of type number
Stacktrace:
SessionNotCreatedError: A new session could not be created. Details: 'newCommandTimeout' must be of type number
    at AndroidUiautomator2Driver.createSession (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\driver.ts:273:13)
    at AndroidUiautomator2Driver.createSession (C:\Users\Lenovo\.appium\node_modules\appium-uiautomator2-driver\lib\driver.js:189:43)
    at AppiumDriver.createSession (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\lib\appium.js:374:56)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
]]></error>
	</testcase>
</testsuite>
